### ISSUE TITLE
Referencing KaTeX css doesn't work...

### ISSUE THREAD

**Issue by cal-id** [cal-id/katex-quick-render#2]
It is currently included in this source with hardcoded font urls. See https://github.com/cal-id/katex-quick-render/blob/master/styles/katex.css

**Comment by cal-id** [comment]
Ideally, there would be a way to use something like `@import` to import the css from node_modules like how katex.js is imported.

**Comment by dschwen** [comment]
You can get the directory of the plugin in using

```
atom.packages.getLoadedPackage('katex-quick-render').path
```

That might allow you to inject the proper style sheet.

**Comment by cal-id** [comment]
Thanks @dschwen. This package no longer includes the hacky copy of katex.css.
